//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccrualPayment
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public int AccrualDescriptionId { get; set; }
        public int AccrualTypeId { get; set; }
        public int AccrualPaymentTypeId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime AccrualPaymentDate { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public int InsertById { get; set; }
    
        public virtual AccrualDescription AccrualDescription { get; set; }
        public virtual Users Users { get; set; }
        public virtual AccrualPaymentType AccrualPaymentType { get; set; }
        public virtual AccrualType AccrualType { get; set; }
        public virtual Funds Funds { get; set; }
    }
}
