//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditSpreadHistory
    {
        public int Id { get; set; }
        public string Isin { get; set; }
        public decimal CreditSpread { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public string Source { get; set; }
        public int UserId { get; set; }
        public int SecurityMasterId { get; set; }
    
        public virtual SecurityMaster SecurityMaster { get; set; }
        public virtual Users Users { get; set; }
    }
}
