//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchangeRates
    {
        public int Id { get; set; }
        public int TickerId { get; set; }
        public System.DateTime ExchangeRateDate { get; set; }
        public decimal CloseExchangeRate { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual CurrencyExchangeRatesTickers CurrencyExchangeRatesTickers { get; set; }
        public virtual Users Users { get; set; }
    }
}
