//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailBwicSecurityLatestPrice
    {
        public int Id { get; set; }
        public int EmailBwicSecurityPriceId { get; set; }
        public string Isin { get; set; }
        public string Price { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual EmailBwicSecurityPrice EmailBwicSecurityPrice { get; set; }
    }
}
