//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergingMarkets
    {
        public int Id { get; set; }
        public int EmergingMarketsGroupId { get; set; }
        public int CountryISOCode { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual EmergingMarketsGroup EmergingMarketsGroup { get; set; }
    }
}
