//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeHolidayLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExchangeHolidayLocation()
        {
            this.ExchangeHoliday = new HashSet<ExchangeHoliday>();
            this.SecurityMasterExchangeHolidayLocation = new HashSet<SecurityMasterExchangeHolidayLocation>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string ShortName { get; set; }
        public string Country { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExchangeHoliday> ExchangeHoliday { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterExchangeHolidayLocation> SecurityMasterExchangeHolidayLocation { get; set; }
    }
}
