//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FactorHistory
    {
        public int Id { get; set; }
        public string ISIN { get; set; }
        public System.DateTime FactorDate { get; set; }
        public decimal Factor { get; set; }
        public Nullable<double> ImpliedFactor { get; set; }
        public System.DateTime LastUpdateTime { get; set; }
        public string UpdatedBy { get; set; }
    }
}
