//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funds
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funds()
        {
            this.AccrualPayment = new HashSet<AccrualPayment>();
            this.FundAccount = new HashSet<FundAccount>();
            this.FundApplicationRule = new HashSet<FundApplicationRule>();
            this.FundCommitment = new HashSet<FundCommitment>();
            this.FundCommitmentLevel = new HashSet<FundCommitmentLevel>();
            this.FundContact = new HashSet<FundContact>();
            this.FundCurrencyProperty = new HashSet<FundCurrencyProperty>();
            this.FundGav = new HashSet<FundGav>();
            this.FundInvestor = new HashSet<FundInvestor>();
            this.FundLeverage = new HashSet<FundLeverage>();
            this.FundNav = new HashSet<FundNav>();
            this.FundPerformanceSummary = new HashSet<FundPerformanceSummary>();
            this.FundPosition = new HashSet<FundPosition>();
            this.FundProfitAndLoss = new HashSet<FundProfitAndLoss>();
            this.FundProperty = new HashSet<FundProperty>();
            this.FundRule = new HashSet<FundRule>();
            this.FundSummary = new HashSet<FundSummary>();
            this.FundTradeExtractionType = new HashSet<FundTradeExtractionType>();
            this.FundTradeExtractionTypeContact = new HashSet<FundTradeExtractionTypeContact>();
            this.OperationsTrades = new HashSet<OperationsTrades>();
            this.SecurityMasterGlobalEthicalStandardFund = new HashSet<SecurityMasterGlobalEthicalStandardFund>();
            this.ShareClass = new HashSet<ShareClass>();
            this.Trades = new HashSet<Trades>();
        }
    
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string LegalName { get; set; }
        public string DbAccountNumber { get; set; }
        public int Active { get; set; }
        public int FundTypeId { get; set; }
        public string ShortName { get; set; }
        public int FundPerformanceCalculationTypeId { get; set; }
        public int MarginCallThreshold { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccrualPayment> AccrualPayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundAccount> FundAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundApplicationRule> FundApplicationRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundCommitment> FundCommitment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundCommitmentLevel> FundCommitmentLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundContact> FundContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundCurrencyProperty> FundCurrencyProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundGav> FundGav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundInvestor> FundInvestor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundLeverage> FundLeverage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundNav> FundNav { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundPerformanceSummary> FundPerformanceSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundPosition> FundPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundProfitAndLoss> FundProfitAndLoss { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundProperty> FundProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundRule> FundRule { get; set; }
        public virtual FundType FundType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundSummary> FundSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundTradeExtractionType> FundTradeExtractionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundTradeExtractionTypeContact> FundTradeExtractionTypeContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationsTrades> OperationsTrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterGlobalEthicalStandardFund> SecurityMasterGlobalEthicalStandardFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareClass> ShareClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trades> Trades { get; set; }
    }
}
