//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundPosition
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public System.DateTime PositionDate { get; set; }
        public string ISIN { get; set; }
        public double Principal { get; set; }
        public double Interest { get; set; }
        public double FundPosition1 { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> PrincipalIncome { get; set; }
        public Nullable<decimal> PrincipalInterest { get; set; }
        public Nullable<decimal> PrincipalTotal { get; set; }
        public Nullable<decimal> DailyChange { get; set; }
        public Nullable<decimal> SingleDayCarry { get; set; }
        public Nullable<decimal> Principal_G_L_ { get; set; }
        public Nullable<decimal> MarkToMarket { get; set; }
        public Nullable<decimal> Fx { get; set; }
        public Nullable<decimal> Trading { get; set; }
        public Nullable<decimal> Unexplained { get; set; }
        public Nullable<decimal> PrincipalReceived { get; set; }
        public Nullable<decimal> InterestReceived { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> FxRate { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public string TradeType { get; set; }
        public Nullable<decimal> CurrentFactor { get; set; }
    
        public virtual Funds Funds { get; set; }
    }
}
