//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundRuleBreach
    {
        public int Id { get; set; }
        public int FundRuleId { get; set; }
        public System.DateTime DateEntered { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public Nullable<int> Suppressed { get; set; }
        public Nullable<int> SuppressedByUserId { get; set; }
        public Nullable<int> Reviewed { get; set; }
        public Nullable<int> ReviewedByUserId { get; set; }
        public Nullable<decimal> BreachPercentage { get; set; }
        public string Notes { get; set; }
    
        public virtual FundRule FundRule { get; set; }
    }
}
