//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundLeverage
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public System.DateTime FundLeverageDate { get; set; }
        public decimal BondTotal { get; set; }
        public decimal CdsTotal { get; set; }
        public decimal CdsInterestTotal { get; set; }
        public decimal FxForwardTotal { get; set; }
        public decimal FxForwardQuantityTotal { get; set; }
        public decimal FundNav { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual Funds Funds { get; set; }
    }
}
