//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FundProfitAndLoss
    {
        public int Id { get; set; }
        public int FundId { get; set; }
        public System.DateTime Date { get; set; }
        public int SecurityId { get; set; }
        public decimal Quantity { get; set; }
        public decimal Factor { get; set; }
        public decimal Price { get; set; }
        public decimal FxRate { get; set; }
        public decimal NotionalLocalTotal { get; set; }
        public decimal CashLocalTotal { get; set; }
        public decimal NotionalTotal { get; set; }
        public decimal CashTotal { get; set; }
        public decimal Total { get; set; }
        public decimal LocalTotal { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual Funds Funds { get; set; }
        public virtual SecurityMaster SecurityMaster { get; set; }
    }
}
