//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FXForwardRate
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public System.DateTime FxForwardRateDate { get; set; }
        public decimal AskPrice { get; set; }
        public decimal BidPrice { get; set; }
        public int DaysToMaturity { get; set; }
        public Nullable<System.DateTime> InsertDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
