//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationsTrades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OperationsTrades()
        {
            this.Trades1 = new HashSet<Trades>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TradeId { get; set; }
        public string Isin { get; set; }
        public string BuySell { get; set; }
        public Nullable<System.DateTime> TradeDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> SettlementDate { get; set; }
        public string SettlementType { get; set; }
        public string CounterpartySalesContact { get; set; }
        public string StepInorOutCpty { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> CDSSpread { get; set; }
        public string TradeFlat { get; set; }
        public Nullable<System.DateTime> FeeSettleDate { get; set; }
        public string RecapConfirmed { get; set; }
        public Nullable<bool> CMBSConvention { get; set; }
        public string InterestCap { get; set; }
        public string CapType { get; set; }
        public string StepUpApplicable { get; set; }
        public string DRDApplicable { get; set; }
        public string AdditionalICE { get; set; }
        public Nullable<System.DateTime> ProcessDateTime { get; set; }
        public Nullable<double> LocalNetAmount { get; set; }
        public Nullable<double> BaseNetAmount { get; set; }
        public Nullable<double> SettlementAmount { get; set; }
        public Nullable<double> Interest { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<int> OperationsId { get; set; }
        public int TradeTypeId { get; set; }
        public int FundId { get; set; }
        public int CounterPartyId { get; set; }
        public Nullable<int> StepInOrOutCounterPartyId { get; set; }
        public Nullable<System.DateTime> AccrueFromDate { get; set; }
        public Nullable<System.DateTime> RecapConfirmedUpdateDateTime { get; set; }
        public Nullable<System.DateTime> TradeCreatedDateTime { get; set; }
        public Nullable<System.DateTime> TradeCancelledDateTime { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<decimal> InitialMarginPercentage { get; set; }
        public Nullable<decimal> InitialMarginAmount { get; set; }
        public Nullable<decimal> FXRate { get; set; }
        public string Status { get; set; }
    
        public virtual Counterparty Counterparty { get; set; }
        public virtual Counterparty Counterparty1 { get; set; }
        public virtual Funds Funds { get; set; }
        public virtual Trades Trades { get; set; }
        public virtual TradeType TradeType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trades> Trades1 { get; set; }
    }
}
