//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string User { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    }
}
