//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistoryLog
    {
        public int Id { get; set; }
        public string Ticker { get; set; }
        public decimal Price { get; set; }
        public System.DateTime PriceDate { get; set; }
        public int HistoryActionId { get; set; }
        public int HistoryStatusId { get; set; }
        public int UserId { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public Nullable<int> ApproverId { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
    
        public virtual HistoryAction HistoryAction { get; set; }
        public virtual HistoryStatus HistoryStatus { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
