//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCashflowExecutionRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskCashflowExecutionRun()
        {
            this.RiskCashflowDetail = new HashSet<RiskCashflowDetail>();
            this.RiskCashflowResult = new HashSet<RiskCashflowResult>();
        }
    
        public int Id { get; set; }
        public int RiskCashflowExecutionId { get; set; }
        public Nullable<int> RiskCashflowInputParameterId { get; set; }
        public Nullable<int> RiskcashflowDefaultIsinId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowDetail> RiskCashflowDetail { get; set; }
        public virtual RiskCashflowExecution RiskCashflowExecution { get; set; }
        public virtual RiskCashflowInputParameter RiskCashflowInputParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowResult> RiskCashflowResult { get; set; }
    }
}
