//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskValuationRunDetailResult
    {
        public int Id { get; set; }
        public int RiskExecutionTaskRunId { get; set; }
        public Nullable<decimal> SeniorDefaultTime { get; set; }
        public Nullable<decimal> MezzDefaultTime { get; set; }
        public Nullable<decimal> JuniorDefaultTime { get; set; }
        public Nullable<decimal> SeniorSwapResult { get; set; }
        public Nullable<decimal> MezzSwapResult { get; set; }
        public Nullable<decimal> JuniorSwapResult { get; set; }
        public Nullable<decimal> SeniorSwapRate { get; set; }
        public Nullable<decimal> MezzSwapRate { get; set; }
        public Nullable<decimal> JuniorSwapRate { get; set; }
        public Nullable<decimal> SeniorPercentage { get; set; }
        public Nullable<decimal> MezzPercentage { get; set; }
        public Nullable<decimal> JuniorPercentage { get; set; }
        public int type { get; set; }
    }
}
