//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskValuationRunDetailCreditShift
    {
        public int Id { get; set; }
        public int RiskExecutionTaskRunId { get; set; }
        public decimal Uniform { get; set; }
        public decimal StandardNormal { get; set; }
        public decimal CorrelatedNormal { get; set; }
        public decimal CorrelatedUniform { get; set; }
        public decimal DefaultIntensity { get; set; }
        public decimal DefaultTime { get; set; }
        public decimal DefaultPercentage { get; set; }
        public decimal SumDefaultPercentage { get; set; }
        public decimal InverseStandardNormal { get; set; }
        public decimal InverseCorrelatedNormal { get; set; }
        public decimal InverseCorrelatedUniform { get; set; }
        public decimal InverseDefaultIntensity { get; set; }
        public decimal InverseDefaultTime { get; set; }
        public decimal InverseDefaultPercentage { get; set; }
        public decimal InverseSumDefaultPercentage { get; set; }
    }
}
