//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskResult
    {
        public int Id { get; set; }
        public decimal SwapRate { get; set; }
        public int NumberOfAssets { get; set; }
        public Nullable<decimal> AverageRecovery { get; set; }
        public Nullable<decimal> PoolExpectedLoss { get; set; }
        public Nullable<decimal> SeniorExpectedLoss { get; set; }
        public Nullable<decimal> MezzExpectedLoss { get; set; }
        public Nullable<decimal> JuniorExpectedLoss { get; set; }
        public Nullable<decimal> SeniorExpectedPresentValueLoss { get; set; }
        public Nullable<decimal> MezzExpectedPresentValueLoss { get; set; }
        public Nullable<decimal> JuniorExpectedPresentValueLoss { get; set; }
        public int RiskExecutionTaskInputParameterRunId { get; set; }
        public int RiskExecutionTaskExecutionTypeId { get; set; }
    
        public virtual RiskExecutionTaskExecutionType RiskExecutionTaskExecutionType { get; set; }
        public virtual RiskExecutionTaskInputParameterRun RiskExecutionTaskInputParameterRun { get; set; }
    }
}
