//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskInputParameterRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskExecutionTaskInputParameterRun()
        {
            this.RiskExecutionTaskCreditShiftRun = new HashSet<RiskExecutionTaskCreditShiftRun>();
            this.RiskExecutionTaskPortfolioDetail = new HashSet<RiskExecutionTaskPortfolioDetail>();
            this.RiskExecutionTaskResult = new HashSet<RiskExecutionTaskResult>();
            this.RiskExecutionTaskRun = new HashSet<RiskExecutionTaskRun>();
            this.RiskPoolResult = new HashSet<RiskPoolResult>();
        }
    
        public int Id { get; set; }
        public int RiskExecutionTaskId { get; set; }
        public int RiskExecutionTaskInputParametersId { get; set; }
    
        public virtual RiskExecutionTask RiskExecutionTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskCreditShiftRun> RiskExecutionTaskCreditShiftRun { get; set; }
        public virtual RiskExecutionTaskInputParameter RiskExecutionTaskInputParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskPortfolioDetail> RiskExecutionTaskPortfolioDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskResult> RiskExecutionTaskResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskRun> RiskExecutionTaskRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskPoolResult> RiskPoolResult { get; set; }
    }
}
