//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskPoolDetailAmortisation
    {
        public int Id { get; set; }
        public int RiskPoolId { get; set; }
        public string Isin { get; set; }
        public decimal OriginalNotional { get; set; }
        public decimal CurrentLosses { get; set; }
        public decimal Amortisation { get; set; }
        public decimal PercentageAdjuster { get; set; }
        public decimal AdjustedAmortisation { get; set; }
        public decimal AdjustedLosses { get; set; }
    
        public virtual RiskPool RiskPool { get; set; }
    }
}
