//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskRunResult
    {
        public int Id { get; set; }
        public int RiskExecutionTaskRunId { get; set; }
        public decimal PoolExpectedLoss { get; set; }
        public decimal SeniorExpectedLoss { get; set; }
        public decimal MezzExpectedLoss { get; set; }
        public decimal JuniorExpectedLoss { get; set; }
        public decimal SeniorExpectedPresentValueLoss { get; set; }
        public decimal MezzExpectedPresentValueLoss { get; set; }
        public decimal JuniorExpectedPresentValueLoss { get; set; }
        public int RiskExecutionTaskExecutionTypeId { get; set; }
    
        public virtual RiskExecutionTaskExecutionType RiskExecutionTaskExecutionType { get; set; }
        public virtual RiskExecutionTaskRun RiskExecutionTaskRun { get; set; }
    }
}
