//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskPool
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskPool()
        {
            this.RiskExecutionTaskCreditShiftRun = new HashSet<RiskExecutionTaskCreditShiftRun>();
            this.RiskExecutionTaskInputParameter = new HashSet<RiskExecutionTaskInputParameter>();
            this.RiskExecutionTaskInputParameterNightly = new HashSet<RiskExecutionTaskInputParameterNightly>();
            this.RiskPoolDetail = new HashSet<RiskPoolDetail>();
            this.RiskPoolDetailAmortisation = new HashSet<RiskPoolDetailAmortisation>();
            this.SecurityMasterRiskPoolMapping = new HashSet<SecurityMasterRiskPoolMapping>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public Nullable<decimal> PoolValue { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> InitialPoolValue { get; set; }
        public Nullable<decimal> Amortisation { get; set; }
        public Nullable<decimal> Losses { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskCreditShiftRun> RiskExecutionTaskCreditShiftRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskInputParameter> RiskExecutionTaskInputParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskInputParameterNightly> RiskExecutionTaskInputParameterNightly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskPoolDetail> RiskPoolDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskPoolDetailAmortisation> RiskPoolDetailAmortisation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterRiskPoolMapping> SecurityMasterRiskPoolMapping { get; set; }
    }
}
