//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskPortfolioDetail
    {
        public int Id { get; set; }
        public int RiskExecutionTaskInputParameterRunId { get; set; }
        public string Isin { get; set; }
        public int IndustryCode { get; set; }
        public decimal CreditSpread { get; set; }
        public decimal Position { get; set; }
        public decimal Recovery { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public decimal WAL { get; set; }
        public decimal Intensity { get; set; }
        public double Factor { get; set; }
        public int SecurityMasterId { get; set; }
    
        public virtual RiskExecutionTaskInputParameterRun RiskExecutionTaskInputParameterRun { get; set; }
        public virtual SecurityMaster SecurityMaster { get; set; }
    }
}
