//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskPoolResult
    {
        public int Id { get; set; }
        public int RiskExecutionTaskInputParameterRunId { get; set; }
        public decimal PoolValue { get; set; }
        public decimal SeniorTranching { get; set; }
        public decimal MezzTranching { get; set; }
        public decimal JuniorTranching { get; set; }
        public System.DateTime InsertDateTime { get; set; }
    
        public virtual RiskExecutionTaskInputParameterRun RiskExecutionTaskInputParameterRun { get; set; }
    }
}
