//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskInputParameter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskExecutionTaskInputParameter()
        {
            this.RiskExecutionTaskInputParameterRun = new HashSet<RiskExecutionTaskInputParameterRun>();
        }
    
        public int Id { get; set; }
        public int RiskPoolId { get; set; }
        public decimal IntraIndustry { get; set; }
        public decimal CrossIndustry { get; set; }
        public int NumberOfSimulations { get; set; }
        public Nullable<decimal> SwapRateRange { get; set; }
        public decimal SeniorSize { get; set; }
        public decimal MezzSize { get; set; }
        public decimal JuniorSize { get; set; }
        public int SimulationTypeId { get; set; }
        public Nullable<decimal> SpreadMultiplier { get; set; }
        public Nullable<decimal> SpreadShift { get; set; }
        public Nullable<decimal> RecoveryMultiplier { get; set; }
        public Nullable<decimal> RecoveryShift { get; set; }
        public Nullable<decimal> WALMultiplier { get; set; }
        public Nullable<decimal> WALShift { get; set; }
    
        public virtual RiskExecutionSimulationType RiskExecutionSimulationType { get; set; }
        public virtual RiskPool RiskPool { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskInputParameterRun> RiskExecutionTaskInputParameterRun { get; set; }
    }
}
