//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCashflowDetail
    {
        public int Id { get; set; }
        public int CashflowParameterRundId { get; set; }
        public string Isin { get; set; }
        public System.DateTime CashflowDate { get; set; }
        public decimal Coupon { get; set; }
        public decimal Cashflow { get; set; }
        public decimal Principal { get; set; }
        public decimal Balance { get; set; }
        public decimal Loss { get; set; }
        public int SecurityMasterId { get; set; }
    
        public virtual RiskCashflowExecutionRun RiskCashflowExecutionRun { get; set; }
        public virtual SecurityMaster SecurityMaster { get; set; }
    }
}
