//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskInputParameterNightly
    {
        public int Id { get; set; }
        public int RiskPoolId { get; set; }
        public Nullable<decimal> IntraIndustry { get; set; }
        public Nullable<decimal> CrossIndustry { get; set; }
        public Nullable<int> NumberOfSimulations { get; set; }
        public Nullable<decimal> SwapRateRange { get; set; }
        public Nullable<decimal> SeniorSize { get; set; }
        public Nullable<decimal> MezzSize { get; set; }
        public Nullable<decimal> JuniorSize { get; set; }
        public Nullable<int> SimulationTypeId { get; set; }
        public Nullable<decimal> SpreadMultiplier { get; set; }
        public Nullable<decimal> SpreadShift { get; set; }
        public Nullable<decimal> RecoveryMultiplier { get; set; }
        public Nullable<decimal> RecoveryShift { get; set; }
        public Nullable<decimal> WALMultiplier { get; set; }
        public Nullable<decimal> WALShift { get; set; }
    
        public virtual RiskExecutionSimulationType RiskExecutionSimulationType { get; set; }
        public virtual RiskPool RiskPool { get; set; }
    }
}
