//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskCashflowIsinProperty
    {
        public int Id { get; set; }
        public string Isin { get; set; }
        public int RiskCashflowIsinPropertyDescriptionId { get; set; }
        public string Value { get; set; }
        public int SecurityMasterId { get; set; }
    
        public virtual RiskCashflowIsinPropertyDescription RiskCashflowIsinPropertyDescription { get; set; }
        public virtual SecurityMaster SecurityMaster { get; set; }
    }
}
