//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiskExecutionTaskRun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RiskExecutionTaskRun()
        {
            this.RiskExecutionTaskRunResult = new HashSet<RiskExecutionTaskRunResult>();
            this.RiskExecutionTaskValuationRunDetail = new HashSet<RiskExecutionTaskValuationRunDetail>();
        }
    
        public int Id { get; set; }
        public int ExecutionRun { get; set; }
        public int RiskExecutionTaskInputParameterRunId { get; set; }
    
        public virtual RiskExecutionTaskInputParameterRun RiskExecutionTaskInputParameterRun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskRunResult> RiskExecutionTaskRunResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskValuationRunDetail> RiskExecutionTaskValuationRunDetail { get; set; }
    }
}
