//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule()
        {
            this.ScheduleExecutionQueue = new HashSet<ScheduleExecutionQueue>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int TaskId { get; set; }
        public string ScheculeType { get; set; }
        public System.TimeSpan ExecutionTime { get; set; }
        public Nullable<int> ExecuteNow { get; set; }
    
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleExecutionQueue> ScheduleExecutionQueue { get; set; }
    }
}
