//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleExecutionQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleExecutionQueue()
        {
            this.ScheduleExecutionErrorLog = new HashSet<ScheduleExecutionErrorLog>();
        }
    
        public int Id { get; set; }
        public int ScheduleId { get; set; }
        public int StatusId { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public Nullable<System.DateTime> DateExecuted { get; set; }
        public Nullable<int> ExecuteNow { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string UserId { get; set; }
    
        public virtual Schedule Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScheduleExecutionErrorLog> ScheduleExecutionErrorLog { get; set; }
        public virtual TaskExecutionStatus TaskExecutionStatus { get; set; }
    }
}
