//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecurityMaster()
        {
            this.CreditSpreadHistory = new HashSet<CreditSpreadHistory>();
            this.FundProfitAndLoss = new HashSet<FundProfitAndLoss>();
            this.RiskCashflowDefaultIsin = new HashSet<RiskCashflowDefaultIsin>();
            this.RiskCashflowDetail = new HashSet<RiskCashflowDetail>();
            this.RiskCashflowFieldProperty = new HashSet<RiskCashflowFieldProperty>();
            this.RiskCashflowInputParameter = new HashSet<RiskCashflowInputParameter>();
            this.RiskCashflowInputParameterDefaults = new HashSet<RiskCashflowInputParameterDefaults>();
            this.RiskCashflowInputParameterNightly = new HashSet<RiskCashflowInputParameterNightly>();
            this.RiskCashflowIsinProperty = new HashSet<RiskCashflowIsinProperty>();
            this.RiskCashflowResult = new HashSet<RiskCashflowResult>();
            this.RiskExecutionTaskPortfolioDetail = new HashSet<RiskExecutionTaskPortfolioDetail>();
            this.RiskPoolDetail = new HashSet<RiskPoolDetail>();
            this.SecurityMasterExchangeHolidayLocation = new HashSet<SecurityMasterExchangeHolidayLocation>();
            this.SecurityMasterNotification = new HashSet<SecurityMasterNotification>();
            this.SecurityMasterRiskPoolMapping = new HashSet<SecurityMasterRiskPoolMapping>();
            this.SecurityMasterSensitivityReport = new HashSet<SecurityMasterSensitivityReport>();
        }
    
        public int Id { get; set; }
        public string ISIN { get; set; }
        public string BloombergID { get; set; }
        public string Description { get; set; }
        public string Currency { get; set; }
        public string Cusip { get; set; }
        public string Type { get; set; }
        public string Type2 { get; set; }
        public string Type3 { get; set; }
        public string BondCalendar { get; set; }
        public string BondPayGap { get; set; }
        public string Callable { get; set; }
        public Nullable<double> CallTrigger { get; set; }
        public string CDSAccrualDays { get; set; }
        public string CDSPayCalendar { get; set; }
        public string CDSPayGap { get; set; }
        public Nullable<double> CollateralPoolFactor { get; set; }
        public Nullable<int> CouponFrequency { get; set; }
        public string CouponIndex { get; set; }
        public string CouponType { get; set; }
        public string DCF { get; set; }
        public string DeliveryType { get; set; }
        public Nullable<double> FloatFixingDays { get; set; }
        public string NonAccrual { get; set; }
        public Nullable<int> Rolldate { get; set; }
        public Nullable<decimal> Spread { get; set; }
        public Nullable<double> StepUpSpread { get; set; }
        public Nullable<decimal> TrancheOf { get; set; }
        public string CoManager { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string Manager { get; set; }
        public System.DateTime MaturityDate { get; set; }
        public string Servicer { get; set; }
        public string Trustee { get; set; }
        public Nullable<double> Factor { get; set; }
        public Nullable<System.DateTime> FactorDate { get; set; }
        public int SecurityMasterGroupId { get; set; }
        public Nullable<int> IssuerId { get; set; }
        public int SecurityMasterTypeId { get; set; }
        public Nullable<double> InitialSpread { get; set; }
        public Nullable<int> IndustryTypeId { get; set; }
        public Nullable<int> EmergingMarketsTypeId { get; set; }
        public Nullable<int> PrivateSecurity { get; set; }
        public Nullable<int> PoolAssociated { get; set; }
        public Nullable<int> GenerateCashflows { get; set; }
        public int DataProviderId { get; set; }
        public int CountryOfRiskId { get; set; }
        public Nullable<System.DateTime> FirstPaymentDate { get; set; }
        public Nullable<int> StrategyId { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public Nullable<int> PaidDown { get; set; }
    
        public virtual CountryOfRisk CountryOfRisk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditSpreadHistory> CreditSpreadHistory { get; set; }
        public virtual DataProvider DataProvider { get; set; }
        public virtual EmergingMarketsType EmergingMarketsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundProfitAndLoss> FundProfitAndLoss { get; set; }
        public virtual IndustryType IndustryType { get; set; }
        public virtual Issuer Issuer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowDefaultIsin> RiskCashflowDefaultIsin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowDetail> RiskCashflowDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowFieldProperty> RiskCashflowFieldProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowInputParameter> RiskCashflowInputParameter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowInputParameterDefaults> RiskCashflowInputParameterDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowInputParameterNightly> RiskCashflowInputParameterNightly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowIsinProperty> RiskCashflowIsinProperty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskCashflowResult> RiskCashflowResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskExecutionTaskPortfolioDetail> RiskExecutionTaskPortfolioDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RiskPoolDetail> RiskPoolDetail { get; set; }
        public virtual SecurityMasterGroup SecurityMasterGroup { get; set; }
        public virtual SecurityMasterInstrument SecurityMasterInstrument { get; set; }
        public virtual SecurityMasterRegion SecurityMasterRegion { get; set; }
        public virtual SecurityMasterStrategy SecurityMasterStrategy { get; set; }
        public virtual SecurityMasterType SecurityMasterType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterExchangeHolidayLocation> SecurityMasterExchangeHolidayLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterNotification> SecurityMasterNotification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterRiskPoolMapping> SecurityMasterRiskPoolMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterSensitivityReport> SecurityMasterSensitivityReport { get; set; }
    }
}
