//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMasterGlobalEthicalStandard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SecurityMasterGlobalEthicalStandard()
        {
            this.SecurityMasterGlobalEthicalStandardFund = new HashSet<SecurityMasterGlobalEthicalStandardFund>();
        }
    
        public int Id { get; set; }
        public string Isin { get; set; }
        public string Issuer { get; set; }
        public string BloombergDescription { get; set; }
        public System.DateTime DateNotified { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public int InsertById { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SecurityMasterGlobalEthicalStandardFund> SecurityMasterGlobalEthicalStandardFund { get; set; }
    }
}
