//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMasterSensitivityReport
    {
        public int Id { get; set; }
        public int SecurityMasterId { get; set; }
        public string Description { get; set; }
        public int EquityTypeId { get; set; }
        public decimal SeniorDebitOutstanding { get; set; }
        public int RatingTypeId { get; set; }
    
        public virtual EquityType EquityType { get; set; }
        public virtual RatingType RatingType { get; set; }
        public virtual SecurityMaster SecurityMaster { get; set; }
    }
}
