//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityMasterRestrictedList
    {
        public int Id { get; set; }
        public string Isin { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public string ReasonAdded { get; set; }
        public Nullable<System.DateTime> DateRemoved { get; set; }
        public string ReasonRemoved { get; set; }
        public string AdditionalNotes { get; set; }
        public int AddedByUserId { get; set; }
        public Nullable<int> RemovedByUserId { get; set; }
        public int Active { get; set; }
    }
}
