//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareSeriesInvestor
    {
        public int Id { get; set; }
        public int ShareSeriesId { get; set; }
        public int InvestorId { get; set; }
        public Nullable<decimal> NumberOfShares { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Investor Investor { get; set; }
        public virtual ShareSeries ShareSeries { get; set; }
    }
}
