//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareSeriesAmount
    {
        public int Id { get; set; }
        public int ShareSeriesId { get; set; }
        public System.DateTime ShareSeriesNavDate { get; set; }
        public decimal Nav { get; set; }
        public decimal NavPerUnit { get; set; }
        public Nullable<decimal> NavMonthToDate { get; set; }
        public Nullable<decimal> NavQuarterToDate { get; set; }
        public Nullable<decimal> NavYearToDate { get; set; }
        public Nullable<decimal> NavLiveToDate { get; set; }
        public decimal GavPerUnit { get; set; }
        public Nullable<decimal> GavMonthToDate { get; set; }
        public Nullable<decimal> GavQuarterToDate { get; set; }
        public Nullable<decimal> GavYearToDate { get; set; }
        public Nullable<decimal> GavLiveToDate { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public int InsertedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDateTime { get; set; }
        public Nullable<int> Active { get; set; }
    
        public virtual ShareSeries ShareSeries { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
