//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShareClass()
        {
            this.ShareClassPerformanceSummary = new HashSet<ShareClassPerformanceSummary>();
            this.ShareSeries = new HashSet<ShareSeries>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public string DisplayName { get; set; }
        public int FundId { get; set; }
        public decimal PerformanceFee { get; set; }
        public int PerformanceFeeFrequency { get; set; }
        public decimal ManagementFee { get; set; }
        public decimal ManagementFeeFrequency { get; set; }
        public int InsertedBy { get; set; }
        public System.DateTime InsertDatetime { get; set; }
    
        public virtual Funds Funds { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareClassPerformanceSummary> ShareClassPerformanceSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShareSeries> ShareSeries { get; set; }
    }
}
