//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareClassPerformanceSummary
    {
        public int Id { get; set; }
        public System.DateTime SummaryDate { get; set; }
        public int ShareClassId { get; set; }
        public decimal Nav { get; set; }
        public Nullable<decimal> NavPerUnit { get; set; }
        public decimal Gav { get; set; }
        public Nullable<decimal> GavPerUnit { get; set; }
        public decimal NavMonthToDate { get; set; }
        public decimal NavQuarterToDate { get; set; }
        public decimal NavYearToDate { get; set; }
        public decimal NavLiveToDate { get; set; }
        public decimal GavMonthToDate { get; set; }
        public decimal GavQuarterToDate { get; set; }
        public decimal GavYearToDate { get; set; }
        public decimal GavLiveToDate { get; set; }
        public System.DateTime InsertDateTime { get; set; }
        public int InsertedBy { get; set; }
    
        public virtual ShareClass ShareClass { get; set; }
    }
}
