//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskExecutionErrorLog
    {
        public int Id { get; set; }
        public int TaskExecutionQueueId { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public string Error { get; set; }
        public string StackTrace { get; set; }
    
        public virtual TaskExecutionQueue TaskExecutionQueue { get; set; }
    }
}
