//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskExecutionQueue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskExecutionQueue()
        {
            this.TaskExecutionErrorLog = new HashSet<TaskExecutionErrorLog>();
        }
    
        public int Id { get; set; }
        public int StatusId { get; set; }
        public int TaskId { get; set; }
        public System.DateTime ExecutionDate { get; set; }
        public Nullable<System.DateTime> DateExecuted { get; set; }
        public string ParentTrigger { get; set; }
        public Nullable<int> ExecuteNow { get; set; }
        public System.DateTime DateEntered { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string UserId { get; set; }
        public Nullable<int> TaskGroupId { get; set; }
        public Nullable<int> EmailId { get; set; }
        public byte[] FileByte { get; set; }
    
        public virtual Task Task { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskExecutionErrorLog> TaskExecutionErrorLog { get; set; }
        public virtual TaskExecutionStatus TaskExecutionStatus { get; set; }
    }
}
