//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeExtractionLog
    {
        public int Id { get; set; }
        public int TradeId { get; set; }
        public int TradeExtractionTypeId { get; set; }
        public System.DateTime ExtractionDate { get; set; }
    
        public virtual Trades Trades { get; set; }
        public virtual TradeExtractionType TradeExtractionType { get; set; }
    }
}
