//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Astra.EmailPriceChecker.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradeHistory
    {
        public int Id { get; set; }
        public System.DateTime TradeHistoryDate { get; set; }
        public int Reference { get; set; }
        public int Version { get; set; }
        public string Status { get; set; }
        public string Isin { get; set; }
        public string BuySell { get; set; }
        public System.DateTime TradeDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public System.DateTime SettlementDate { get; set; }
        public string SettlementType { get; set; }
        public string CounterpartySalesContact { get; set; }
        public string StepInorOutCpty { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<double> CDSSpread { get; set; }
        public string TradeFlat { get; set; }
        public Nullable<System.DateTime> FeeSettleDate { get; set; }
        public string RecapConfirmed { get; set; }
        public string CMBSConvention { get; set; }
        public string InterestCap { get; set; }
        public string CapType { get; set; }
        public string StepUpApplicable { get; set; }
        public string DRDApplicable { get; set; }
        public string AdditionalICE { get; set; }
        public string FO_Comments { get; set; }
        public string BO_Comments { get; set; }
        public string BrokerName { get; set; }
        public Nullable<double> BrokerFee { get; set; }
        public string BrokerFeeType { get; set; }
        public Nullable<System.DateTime> BrokerFeeSettlementDate { get; set; }
        public Nullable<System.DateTime> ProcessDateTime { get; set; }
        public string AdministratorFileSent { get; set; }
        public Nullable<System.DateTime> AdministratorFileDateTime { get; set; }
        public string CustodianFileSent { get; set; }
        public Nullable<System.DateTime> CustodianFileDateTime { get; set; }
        public Nullable<double> LocalNetAmount { get; set; }
        public Nullable<double> BaseNetAmount { get; set; }
        public double SettlementAmount { get; set; }
        public Nullable<double> Interest { get; set; }
        public string DeliveryType { get; set; }
        public int TraderId { get; set; }
        public Nullable<int> OperationsId { get; set; }
        public int TradeTypeId { get; set; }
        public int FundId { get; set; }
        public int CounterPartyId { get; set; }
        public Nullable<int> StepInOrOutCounterPartyId { get; set; }
        public Nullable<System.DateTime> AccrueFromDate { get; set; }
        public Nullable<System.DateTime> RecapConfirmedUpdateDateTime { get; set; }
        public Nullable<System.DateTime> TradeCreatedDateTime { get; set; }
        public Nullable<System.DateTime> TradeCancelledDateTime { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<decimal> InitialMarginPercentage { get; set; }
        public Nullable<decimal> InitialMarginAmount { get; set; }
        public string SubStatus { get; set; }
        public Nullable<int> TradeUnwind { get; set; }
        public Nullable<decimal> FXRate { get; set; }
        public Nullable<int> OperationsTradeId { get; set; }
        public Nullable<int> FundAccountId { get; set; }
        public Nullable<int> NovationTradeReference { get; set; }
        public Nullable<System.DateTime> OriginalTradeDate { get; set; }
        public string RiskRetentionCompliant { get; set; }
        public string RiskRetentionCompliantSource { get; set; }
    }
}
